server:
  port: 8090

provider:
  coupang:
    client-id:
    vendor_id: A01016365
    secret_key: e437851c7916fe9e853d8cfa25b01da09f8a7d71
    access_key: d662429d-5397-4940-8b29-48d63355a178
    baseUrl:

spring:
  mustache:
    charset: utf-8
    servlet:
      content-type: text/html
    suffix: .html
    prefix: classpath:/static

webdriver:
  chrome:
    driver_id: webdriver.chrome.driver
    driver_path: src/main/resources/lib/chromedriver-win32/chromedriver-win32/chromedriver.exe
#    driver_path: C:/chromedriver-win32/chromedriver-win32/chromedriver.exe

excel:
  default_file_path: C:/test
  name_prefix: pangpang
  name_sufix: .xls
